### ISSUE TITLE
Trying to run this, error...

### ISSUE THREAD

**Issue by scarton** [mantis-ai/semaphore-connect#1]
Any idea how to get past this?

Build file '/home/steve/projects/enron-connector/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'enron-connector'.
> Could not get unknown property 'customTokens' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.

**Comment by jmeekhof** [comment]
Can you post your `build.gradle` file?

**Comment by scarton** [comment]
Sure - thanks.

I took the build.gradle from the repo and added the ext element.

plugins {
  id "net.saliman.properties" version "1.4.6"
  id "com.marklogic.ml-gradle" version "2.7.3"
}
ext {
    customTokens.put("%%SCS_MODULES_DATABASE%%", mlSlcModulesDatabase)
}

**Comment by jmeekhof** [comment]
I see. The `customTokens.put` is part of the `mlAppConfig`. Try something like:

```groovy
ext {
    mlAppConfig {
        customTokens.put("%%SCS_MODULES_DATABASE%%", mlSlcModulesDatabase)
    }
}
```

You'll also need to define `mlSlcModulesDatabase` within your properties file.

**Comment by jmeekhof** [comment]
I've updated the README with the complete instructions.

**Comment by scarton** [comment]
This gets me further, am now stopped by authentication...
Execution failed for task ':mlDeployApp'.
> 401 Unauthorized

Where do I put credentials in the project configs?

**Comment by jmeekhof** [comment]
This uses MarkLogic's [ml-gradle ](https://github.com/marklogic-community/ml-gradle) plugin. You should refer to their instruction on how to use it for complete details. However, to fix your current issue you need to put into your `gradle.properties` or `gradle-local.properties` keys for `mlUser` and `mlPassword`.

```jproperties
mlUser=admin
mlPassword=password
```

**Comment by scarton** [comment]
Thanks. I was trying to avoid learning either gradle or mlGradle.
